<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Pob.Rendering/Pob.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="References/**/*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
