using System.Reflection;

namespace Pob.Data.Behaviours;

/// <summary>
/// Access to the enumerated behaviour contract, <c>behaviour-keys.json</c>, embedded in this
/// assembly. The file is generated by <c>dotnet/tools/behaviour-keys/enumerate.lua</c> and is the
/// authoritative list of every behaviour the Lua data expects a C# implementation for.
/// </summary>
public static class BehaviourManifest
{
    /// <summary>The embedded resource name of the manifest.</summary>
    public const string ResourceName = "Pob.Data.behaviour-keys.json";

    /// <summary>Opens the manifest for reading.</summary>
    public static Stream Open() =>
        typeof(BehaviourManifest).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName)
        ?? throw new InvalidOperationException(
            $"Embedded resource '{ResourceName}' is missing from Pob.Data.");

    /// <summary>Reads the manifest as text.</summary>
    public static string ReadAllText()
    {
        using var stream = Open();
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
